function Bp = get_Mp(in1,in2,in3)
%get_Mp
%    Bp = get_Mp(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:54

a1 = in3(:,1);
a2 = in3(:,2);
p1_3 = in2(7,:);
p2_1 = in2(2,:);
p2_2 = in2(5,:);
p2_3 = in2(8,:);
p3_1 = in2(3,:);
p3_2 = in2(6,:);
p3_3 = in2(9,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = q2+q3;
t5 = a1.^2;
t6 = a2.^2;
t7 = cos(t4);
t8 = a1.*p2_2.*t2;
t9 = a2.*p3_2.*t3;
t10 = p3_1.*t6;
t12 = a1.*a2.*p3_1.*t2;
t11 = t9.*2.0;
t13 = p3_3+t9;
t14 = a1.*p3_2.*t7;
t15 = t13+t14;
t16 = p2_3+p3_3+t8+t10+t11+t12+t14;
Bp = reshape([p1_3+t8+t12+t14+t16+p2_1.*t5+p3_1.*t5,t16,t15,t16,p2_3+p3_3+t10+t11,t13,t15,t13,p3_3],[3,3]);
end
