function Cp = get_Cp(in1,in2,in3,in4)
%get_Cp
%    Cp = get_Cp(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:55

a1 = in4(:,1);
a2 = in4(:,2);
dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
p2_2 = in3(5,:);
p3_1 = in3(3,:);
p3_2 = in3(6,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q2);
t3 = sin(q3);
t4 = dq1.*dq2;
t5 = q2+q3;
t6 = dq1+1.0;
t7 = p2_2.*t2;
t8 = sin(t5);
t9 = a2.*p3_1.*t2;
t10 = a2.*p3_2.*t3;
t12 = dq2+t4+1.0;
t11 = p3_2.*t8;
t13 = a1.*t11;
t14 = t7+t9+t11;
Cp = reshape([-dq3.*(t10+t13+a1.*dq2.*t14),-dq3.*(t10-a1.*t4.*t14),dq2.*dq3.*(t10+dq1.*(t10+t13)),-dq3.*(t10+t13+a1.*dq2.*t6.*t14),-dq3.*t10,dq2.*dq3.*t6.*t10,-dq3.*p3_2.*t12.*(a2.*t3+a1.*t8),-dq3.*t10.*t12,0.0],[3,3]);
end
