function J_dot = get_J_dot(in1,in2,in3)
%get_J_dot
%    J_dot = get_J_dot(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:08

a1 = in3(:,1);
a2 = in3(:,2);
a3 = in3(:,3);
dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = a2.*t3;
t9 = a2.*t5;
t10 = a3.*t6;
t11 = a3.*t7;
t12 = dq3.*t10;
t13 = dq3.*t11;
t16 = t8+t10;
t17 = t9+t11;
t14 = -t12;
t15 = -t13;
t18 = dq2.*t16;
t19 = dq2.*t17;
t20 = -t18;
t21 = -t19;
J_dot = reshape([t14+t20-dq1.*(t16+a1.*cos(q1)),t15+t21-dq1.*(t17+a1.*sin(q1)),0.0,0.0,0.0,0.0,t14+t20-dq1.*t16,t15+t21-dq1.*t17,0.0,0.0,0.0,0.0,t14-dq1.*t10-dq2.*t10,t15-dq1.*t11-dq2.*t11,0.0,0.0,0.0,0.0],[6,3]);
end
