function D = get_D(in1)
%get_D
%    D = get_D(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:53

d1 = in1(10,:);
d2 = in1(11,:);
d3 = in1(12,:);
D = reshape([d1,0.0,0.0,0.0,d2,0.0,0.0,0.0,d3],[3,3]);
end
