function G = get_G(in1,in2)
%get_G
%    G = get_G(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:53

a1 = in2(13,:);
a2 = in2(14,:);
g = in2(16,:);
l1 = in2(4,:);
l2 = in2(5,:);
l3 = in2(6,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = q1+q2;
t4 = a1.*t2;
t5 = cos(t3);
t6 = q3+t3;
t7 = cos(t6);
t8 = a2.*t5;
t9 = l3.*t7;
G = [-g.*m2.*(t4+l2.*t5)-g.*m3.*(t4+t8+t9)-g.*l1.*m1.*t2;-g.*m3.*(t8+t9)-g.*l2.*m2.*t5;-g.*m3.*t9];
end
