function M = get_M(in1,in2)
%get_M
%    M = get_M(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:52

a1 = in2(13,:);
a2 = in2(14,:);
i1 = in2(7,:);
i2 = in2(8,:);
i3 = in2(9,:);
l1 = in2(4,:);
l2 = in2(5,:);
l3 = in2(6,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = q2+q3;
t5 = a1.^2;
t6 = a2.^2;
t7 = l2.^2;
t8 = l3.^2;
t9 = cos(t4);
t10 = m3.*t6;
t11 = m2.*t7;
t12 = m3.*t8;
t13 = a1.*a2.*m3.*t2;
t14 = a1.*l2.*m2.*t2;
t15 = a2.*l3.*m3.*t3;
t16 = t15.*2.0;
t17 = a1.*l3.*m3.*t9;
t18 = i3+t12+t15;
t19 = t17+t18;
t20 = i2+i3+t10+t11+t12+t13+t14+t16+t17;
M = reshape([i1+t13+t14+t17+t20+m2.*t5+m3.*t5+l1.^2.*m1,t20,t19,t20,i2+i3+t10+t11+t12+t16,t18,t19,t18,i3+t12],[3,3]);
end
