function J = get_J(in1,in2)
%get_J
%    J = get_J(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:08

a1 = in2(:,1);
a2 = in2(:,2);
a3 = in2(:,3);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = a2.*t3;
t9 = a2.*t5;
t10 = a3.*t6;
t11 = a3.*t7;
t12 = -t9;
t13 = -t11;
J = reshape([t12+t13-a1.*sin(q1),t8+t10+a1.*cos(q1),0.0,0.0,0.0,1.0,t12+t13,t8+t10,0.0,0.0,0.0,1.0,t13,t10,0.0,0.0,0.0,1.0],[6,3]);
end
