function C = get_C(in1,in2,in3)
%get_C
%    C = get_C(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:53

a1 = in3(13,:);
a2 = in3(14,:);
dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
l2 = in3(5,:);
l3 = in3(6,:);
m2 = in3(2,:);
m3 = in3(3,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q2);
t3 = sin(q3);
t4 = dq1.*dq2;
t5 = q2+q3;
t6 = dq1+1.0;
t7 = a2.*t3;
t8 = sin(t5);
t9 = a2.*m3.*t2;
t10 = l2.*m2.*t2;
t13 = dq2+t4+1.0;
t11 = a1.*t8;
t12 = l3.*m3.*t7;
t14 = l3.*m3.*t8;
t15 = t7+t11;
t17 = t9+t10+t14;
t16 = l3.*m3.*t15;
C = reshape([-dq3.*(t16+a1.*dq2.*t17),-dq3.*(t12-a1.*t4.*t17),dq2.*dq3.*(t12+dq1.*t16),-dq3.*(t16+a1.*dq2.*t6.*t17),-dq3.*t12,dq2.*dq3.*t6.*t12,-dq3.*t13.*t16,-dq3.*t12.*t13,0.0],[3,3]);
end
