function Gp = get_Gp(in1,in2,in3)
%get_Gp
%    Gp = get_Gp(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:55

a1 = in3(:,1);
a2 = in3(:,2);
g = in3(:,4);
p1_2 = in2(4,:);
p2_1 = in2(2,:);
p2_2 = in2(5,:);
p3_1 = in2(3,:);
p3_2 = in2(6,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = q1+q2;
t7 = 1.0./p3_1;
t4 = a1.*t2;
t5 = cos(t3);
t6 = q3+t3;
t8 = cos(t6);
t9 = a2.*t5;
t10 = p3_2.*t7.*t8;
Gp = [-g.*p2_1.*(t4+(p2_2.*t5)./p2_1)-g.*p1_2.*t2-g.*p3_1.*(t4+t9+t10);-g.*p3_1.*(t9+t10)-g.*p2_2.*t5;-g.*p3_2.*t8];
end
