function T_0_i = get_T_0_i(in1,in2)
%get_T_0_i
%    T_0_i = get_T_0_i(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:08

a1 = in2(:,1);
a2 = in2(:,2);
a3 = in2(:,3);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = a1.*t2;
t6 = a1.*t3;
t7 = cos(t4);
t8 = q3+t4;
t9 = sin(t4);
t10 = cos(t8);
t11 = sin(t8);
t12 = a2.*t7;
t13 = a2.*t9;
t14 = -t11;
T_0_i = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,t7,t9,0.0,0.0,-t9,t7,0.0,0.0,0.0,0.0,1.0,0.0,t5,t6,0.0,1.0,t10,t11,0.0,0.0,t14,t10,0.0,0.0,0.0,0.0,1.0,0.0,t5+t12,t6+t13,0.0,1.0,t10,t11,0.0,0.0,t14,t10,0.0,0.0,0.0,0.0,1.0,0.0,t5+t12+a3.*t10,t6+t13+a3.*t11,0.0,1.0],[4,4,4]);
end
