function Y_kin = get_Y_kin(in1,in2,in3)
%get_Y_kin
%    Y_kin = get_Y_kin(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Oct-2025 19:41:08

dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
Y_kin = reshape([-dq1.*sin(q1),dq1.*cos(q1),0.0,0.0,0.0,0.0,-dq1.*t5-dq2.*t5,dq1.*t3+dq2.*t3,0.0,0.0,0.0,0.0,-dq1.*t7-dq2.*t7-dq3.*t7,dq1.*t6+dq2.*t6+dq3.*t6,0.0,0.0,0.0,0.0],[6,3]);
end
