function C = RR_coriolis_matrix(q1,q2,q3,dq1,dq2,dq3)
%RR_coriolis_matrix
%    C = RR_coriolis_matrix(Q1,Q2,Q3,DQ1,DQ2,DQ3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Sep-2025 18:33:09

t2 = sin(q2);
t3 = sin(q3);
t4 = q2+q3;
t5 = dq1+dq2+dq3;
t6 = sin(t4);
t7 = t3./2.0;
t8 = t2.*(3.0./2.0);
t11 = dq3.*t3.*(-1.0./2.0);
t10 = t6./2.0;
t12 = t7+t10;
t13 = t8+t10;
t14 = dq1.*t13;
t15 = dq2.*t13;
t16 = dq3.*t12;
t17 = -t15;
t18 = -t16;
C = reshape([t17+t18,t11+t14,dq2.*t7+dq1.*t12,-t14+t17+t18,t11,t7.*(dq1+dq2),t5.*(t3+t6).*(-1.0./2.0),t3.*t5.*(-1.0./2.0),0.0],[3,3]);
end
