function G = RR_gravity_vector(q1,q2,q3)
%RR_gravity_vector
%    G = RR_gravity_vector(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Sep-2025 18:33:09

t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = cos(t4);
t6 = t3.*1.4715e+1;
t7 = t5.*(9.81e+2./2.0e+2);
G = [t6+t7+cos(q1).*(9.81e+2./4.0e+1);t6+t7;t7];
end
