function B = RR_mass_matrix(q1,q2,q3)
%RR_mass_matrix
%    B = RR_mass_matrix(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Sep-2025 18:33:09

t2 = cos(q2);
t3 = cos(q3);
t4 = q2+q3;
t5 = cos(t4);
t6 = t3./2.0;
t7 = t2.*(3.0./2.0);
t8 = t5./2.0;
t9 = t6+1.0./3.0;
t10 = t8+t9;
t11 = t3+t7+t8+5.0./3.0;
B = reshape([t2.*3.0+t3+t5+4.0,t11,t10,t11,t3+5.0./3.0,t9,t10,t9,1.0./3.0],[3,3]);
end
